# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      # specify the version
      - image: cimg/go:1.22.3
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run: go version
      - run:
          name: "fetch dependencies"
          command: |
            go env
            make init
      - run:
          name: "running test"
          command: make test-race

      - run:
          name: "running lint"
          command: |
            make tool-lint
            make lint

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - /.*/
